roystgnr/MetaPhysicL

- ChangeLog
- INSTALL
- Makefile.am
- NEWS
- README
- src/numerics/include/metaphysicl/dynamicsparsenumberbase.h
- src/numerics/include/metaphysicl/numberarray.h
- src/numerics/include/metaphysicl/numbervector.h
- test/derivs_unit.C
- test/identities_unit.C
- test/sparse_derivs_unit.C
- test/sparse_identities_unit.C
This should include everything added to MetaPhysicL (except the AM_MAINTAINER_MODE setting) as part of https://github.com/libMesh/libmesh/pull/1506, https://github.com/libMesh/libmesh/pull/1510, and https://github.com/libMesh/libmesh/pull/1513.
I chose the list of commits manually from "git log contrib/metaphysicl" there, then stripped out patches with
```
num=1000; for sha in aba77b571b622b9f7c11b0454368ffb8f3e44cd2 f2bcc0ba3bb78937b07a981ff7f75d362bcc9b55 03c82c655548ed46db9b5edd334b7f9370ada90b 8b00b994fbad288647a1604d61392ddc0eaad56a b632fa1de4ba4d4029665d69da7259adfd7c9455 6ee4bba702ea5c83d5e45b6babb17f4ca1a0198f 8fa9edb142d32079779d1a682d6074e043c919fa 013ebeadb2709dd4c3909887dbab2ffaa79cee07 896732d2a0c1ae42625cd608c159e58d00538303 c39064a602ab3e021c7f476f5ea24ff6816afe35; do git …
```
> Fixes ported upstream from libMesh

- configure.ac
- src/Makefile.am
- test/Makefile.am
And avoid warning messages from trying to license stamp read-only
sources when in "make dist".
Thanks to @pbauman for figuring this out in grinsfem/grins@9329336
This fixes #8 for me.
> Don't distribute license utility

- configure.ac
- m4/common/vexcl.m4
With this, VexCL builds work for me with both C++14 and C++11 compilers.
> Avoid adding -std=c++11 if -std=c++14 is working

- configure.ac
- m4/common/ax_cxx_compile_stdcxx.m4
See https://github.com/libMesh/libmesh/pull/1845
@jwpeterson, could you give this a try and see if it catches the bug with your old clang/libstdc++ combination?  If it works then we'll turn it into 0.3.1, rebootstrap, etc.
> Allow manually (and improve auto) disabling modern C++

- src/numerics/include/metaphysicl/dualnumber_surrogate.h
- src/numerics/include/metaphysicl/dualnumber_surrogate_decl.h
- src/numerics/include/metaphysicl/nddualnumber.h
Without copy constructor/assignment operator that accepts a `const` argument, instantiations of stl containers that contain `DualNumberSurrogates` can error out. I've seen this in MOOSE work. I'm not quite sure why these errors aren't produced in the `nd_derivs_unit` test because it instantiates a `std::map` with `DualNumberSurrogate` values.
> Allow canonical copy constructor/assignment argument (const &) for DualNumberSurrogate

- src/numerics/include/metaphysicl/dualnumber_decl.h
Old gcc versions complain about unused parameter in defaulted constructors/assignment operators
> Comment "unused" parameters

- src/numerics/include/metaphysicl/dualnumber.h
- src/numerics/include/metaphysicl/dualnumber_decl.h
- test/nd_derivs_unit.C
Needed for operations like:
```c++
DualNumber<double> new_dn = NotADuckDualNumber<TensorValue<double>>(TensorValue<double>())(0, 0)
```
> DualNumber construction/assignment from DualNumberSurrogate

- src/numerics/include/metaphysicl/dynamicsparsenumberbase.h
- src/numerics/include/metaphysicl/dynamicsparsenumberbase_decl.h
This isn't a great fix but it's the best we can do while still
returning T&
Pinging @lindsayad
> Fix dangling reference return in DSNB::operator[]

- src/numerics/include/metaphysicl/dualnumber.h
- src/numerics/include/metaphysicl/dualnumber_decl.h
This avoids calling conversion constructors
> Add some assignment overloads for DualNumber

- src/numerics/include/metaphysicl/dualnumber.h
- src/numerics/include/metaphysicl/dualnumber_decl.h
- src/numerics/include/metaphysicl/numberarray.h
- src/numerics/include/metaphysicl/numbervector.h
I know we have #13, and I was the one to make the change for `NumberArray` in #11, but I do think we should allow intentional uninitialized data. I see a lot of `bzero` show up in profiling. I don't think that a user who calls `NumberArray a;` and `NumberArray a = NumberArray()` should expect different behavior. I re-read [this discussion](https://github.com/roystgnr/MetaPhysicL/pull/11#discussion_r212089810) quite a few times this morning and had @jwpeterson look at it as well; I guess I'm just not familiar with the second idiom. We both look at the first and second expressions in that discussion and expect to observe the exact same behavior between the two.
> Don't default initialize NumberArray data

- src/Makefile.am
build libmesh in mingw64
> Unknown option: S=../src
https://github.com/roystgnr/MetaPhysicL/blob/0464c02f47aecb9c4c28efc6e342bc02df58a627/src/common/lic_utils/update_license.pl#L31
``print "  -S dir               use dir as location of source-files\n";``
> error Unknown option

- INSTALL
We recently updated the version of automake that libmesh uses to 1.16.1, this PR just re-bootstraps using that automake. This fixes an issue where you end up with diffs in the metaphysicl submodule when running ./bootstrap at the libmesh level.
@roystgnr not sure if you want to tag this or leave it as a branch. Either way I can update libmesh's metaphysicl submodule once it makes it into upstream.
> Re-bootstrap with up to date libmesh autotools.

- src/Makefile.am
- src/core/include/metaphysicl/metaphysicl_common.h
- src/numerics/include/metaphysicl/dynamicsparsenumbervector.h
Currently when compiling in optimized modes we will get warnings in some functions that only use their parameters in debug mode. I created `metaphysicl_dbg_var` as an analog to `libmesh_dbg_var` to address this issue.
> Create metaphysicl_dbg_var to eliminate compiler warnings 

- src/numerics/include/metaphysicl/dualexpression.h
- src/numerics/include/metaphysicl/dualnumber.h
We were previously trying to avoid an extra pow call by simply
dividing the result of the original call by the base, but this gives
0/0 => NaN when the base is 0, even for the b > 1 case where the
derivative *should* be well-defined.
Hopefully this fixes the aside @dschwen pointed out in #35.
This ends up forcing an extra std::pow call in the DualNumber case, which isn't great for efficiency, but isn't the yet-another-if_else efficiency disaster I was fearing.
> Fix std::pow(0,b>1) derivatives

- test/derivs_unit.C
This adds a unit test that would have been broken before the fix in #49, to make sure we don't revert it.
More controversially, this adds a unit test that may break on some C++ implementations!  I'm still not sure what the ideal fix is for ```pow(dn,1)``` where ```dn == 0``` is a ```DualNumber``` or a ```DualExpression```, but it turns out that the existing code actually *works* for many C++ implementations, because the ISO C standard says that for ```pow(0,0)``` "a domain error may occur", not *must* occur, and apparently a lot of implementations have decided to return "1" here, exactly what we'd hope for, rather than "0" or "NaN".  So now I'm tempted to just let that efficient-but-technically-incorrect code slide until someone sees "make check" fail and we thereby discover an system …
> More tests for pow(Dual*)

- src/numerics/include/metaphysicl/dualnumber.h
This is mostly @rwcarlsen's work. I'm going to let him give a more detailed description for why this is desired, but it's mostly for avoiding memset and memcpy calls as well as encouraging vectorization.
@rwcarlsen, can you check and see whether you're still getting the desired performance with the commits I added?
> Reduce temporary creation

- src/core/include/metaphysicl/compare_types.h
- test/complex_derivs_unit.C
Previously we had CompareTypes defined for ops between
std::complex<U> and T where T != U, but not for T == U.
This remedies that
> Allow operations between std::complex<T> and T

- src/Makefile.am
- src/numerics/include/metaphysicl/dualdynamicsparsenumberarray_decl.h
- src/numerics/include/metaphysicl/dualdynamicsparsenumbervector_decl.h
- src/numerics/include/metaphysicl/dualnumber.h
- src/numerics/include/metaphysicl/dualnumber_decl.h
- src/numerics/include/metaphysicl/dualnumber_forward.h
- src/numerics/include/metaphysicl/dualnumber_surrogate_decl.h
- src/numerics/include/metaphysicl/dualnumberarray.h
- src/numerics/include/metaphysicl/dualnumbervector.h
- src/numerics/include/metaphysicl/dualsemidynamicsparsenumberarray_decl.h
- src/numerics/include/metaphysicl/dualsparsenumberarray.h
- src/numerics/include/metaphysicl/dualsparsenumberstruct.h
- src/numerics/include/metaphysicl/dualsparsenumbervector.h
- src/numerics/include/metaphysicl/numberarray.h
I expect this one to be a little controversial. I'd suggest looking at idaholab/moose#14701 for context. We would like to remove templating from the MOOSE AD user experience without sacrificing our current performance. With a `static bool do_derivatives` member we can turn off derivative calculation except when we really want it (e.g. during Jacobian evaluation). The most annoying thing about this to me is "possibly uninitialized` warnings from the compiler, which unfortunately could in cases correspond to "definitely uninitialized". 
I will say that for the `powerlaw_sum` test case in https://github.com/idaholab/moose/pull/14701#issuecomment-587182782, this PR reduces the computation time for a non-sparse derivative container from 55 to 6 seconds, while for a sparse container it reduces …
> Add boolean to turn off derivative calculations

- configure.ac
Boost macros appear to rely on the fact that libtool has already been invoked as indicated by the configure error [here](https://civet.inl.gov/job/477902/):
> checking for the Boost system library... configure: error: the libext variable is empty, did you invoke Libtool?
This appears to be the first time in our test harness MetaPhysicL was able to probe an available BOOST because with the new configure introduced in #58 we pick up the includes and libs available in the conda environment:
```bash
$ mpicxx -show
x86_64-conda_cos6-linux-gnu-c++ -march=nocona -mtune=haswell -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/lindad/.conda/envs/moose/lib -Wl,-rpath-link,/home/lindad/.conda/envs/moose/lib …
```
> Move LT_INIT to before any BOOST macro invocation

- src/numerics/include/metaphysicl/dualnumber_decl.h
We have vector and vector-vector material properties in MOOSE for
which it can be useful to call MetaPhysicL::raw_value. This will
also be useful for the AD stuff in libMesh that I'm working on
given how we store `phi` etc.
> Add RawType<vector<DualNumber>> and RawType<vector<vector<DualNumber>>>

- configure.ac
- m4/acsm_cxx_tests.m4
This gives us finer and more generalizeable control over what tests we
run and what switches we try to add.
> Use ACSM_CXX_COMPILER_STANDARD
